// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1VzQ7hAizfzFYmrklfOXdRXIHp-7W38Q',
    appId: '1:215086108466:web:7bd3b440521146648f112b',
    messagingSenderId: '215086108466',
    projectId: 'rablo-fb0e3',
    authDomain: 'rablo-fb0e3.firebaseapp.com',
    storageBucket: 'rablo-fb0e3.firebasestorage.app',
    measurementId: 'G-C73ZHQWN9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvaVQbYx7JegTF-WGpgjhW3Y4uceIArO0',
    appId: '1:215086108466:android:330fe791c804c0ae8f112b',
    messagingSenderId: '215086108466',
    projectId: 'rablo-fb0e3',
    storageBucket: 'rablo-fb0e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcdHvc-uFxKBcT4Cfr5cZSHjYmfUapnYM',
    appId: '1:215086108466:ios:342733ef82494c6d8f112b',
    messagingSenderId: '215086108466',
    projectId: 'rablo-fb0e3',
    storageBucket: 'rablo-fb0e3.firebasestorage.app',
    iosBundleId: 'com.example.newAssigment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcdHvc-uFxKBcT4Cfr5cZSHjYmfUapnYM',
    appId: '1:215086108466:ios:342733ef82494c6d8f112b',
    messagingSenderId: '215086108466',
    projectId: 'rablo-fb0e3',
    storageBucket: 'rablo-fb0e3.firebasestorage.app',
    iosBundleId: 'com.example.newAssigment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1VzQ7hAizfzFYmrklfOXdRXIHp-7W38Q',
    appId: '1:215086108466:web:eb5d4fcd94fe7ff28f112b',
    messagingSenderId: '215086108466',
    projectId: 'rablo-fb0e3',
    authDomain: 'rablo-fb0e3.firebaseapp.com',
    storageBucket: 'rablo-fb0e3.firebasestorage.app',
    measurementId: 'G-XHCZPRSB6N',
  );
}
